In [1]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

import os
os.chdir('/content/drive/MyDrive/DSSI/Project/code')
import utils

np.random.seed(42)

plt.rcParams['figure.figsize'] = (12, 4)
plt.rcParams['axes.grid'] = True
plt.rcParams['grid.alpha'] = 0.3
%matplotlib inline

print('All imports successful!')

Mounted at /content/drive
All imports successful!

In [25]:
counts_by_county = pd.read_excel('/content/drive/MyDrive/DSSI/Project/data/Cocci Case Counts by County and Month, 2001-2024.xlsx', header=1)
counts_by_county = counts_by_county.drop(counts_by_county.columns[[3,4]], axis=1)
counts_by_county.columns = ['County','Year-Month','Case_Count']
counts_by_county['Case_Count'] = pd.to_numeric(counts_by_county['Case_Count'], errors='coerce')
counts_by_county['Case_Count'] = counts_by_county['Case_Count'].fillna(0)
counts_by_county['County'] = counts_by_county['County'].str.title()
counts_by_county

        County Year-Month  Case_Count
0      Alameda    2001_01         0.0
1      Alameda    2001_02         0.0
2      Alameda    2001_03         2.0
3      Alameda    2001_04         2.0
4      Alameda    2001_05         0.0
...        ...        ...         ...
16699     Yuba    2024_08         0.0
16700     Yuba    2024_09         0.0
16701     Yuba    2024_10         0.0
16702     Yuba    2024_11         0.0
16703     Yuba    2024_12         0.0

[16704 rows x 3 columns]

In [26]:
county_totals = counts_by_county.groupby('County')['Case_Count'].sum().reset_index()
county_totals

             County  Case_Count
0           Alameda      1048.0
1            Alpine         0.0
2            Amador         0.0
3             Butte         0.0
4         Calaveras         0.0
5            Colusa         0.0
6      Contra Costa      1410.0
7         Del Norte         0.0
8         El Dorado         0.0
9            Fresno     10925.0
10            Glenn         0.0
11         Humboldt         0.0
12         Imperial         0.0
13             Inyo         0.0
14             Kern     46138.0
15            Kings      2873.0
16             Lake         0.0
17           Lassen         0.0
18      Los Angeles     14719.0
19           Madera        61.0
20            Marin        70.0
21         Mariposa         0.0
22        Mendocino         0.0
23           Merced      1363.0
24            Modoc         0.0
25             Mono         0.0
26         Monterey      2086.0
27             Napa         0.0
28           Nevada         0.0
29           Orange      3140.0
30           Placer       100.0
31           Plumas         0.0
32        Riverside      3377.0
33       Sacramento       771.0
34       San Benito         0.0
35   San Bernardino      1983.0
36        San Diego      4909.0
37    San Francisco       289.0
38      San Joaquin      2877.0
39  San Luis Obispo      3860.0
40        San Mateo       299.0
41    Santa Barbara      1059.0
42      Santa Clara       931.0
43       Santa Cruz       176.0
44           Shasta         0.0
45           Sierra         0.0
46         Siskiyou         0.0
47           Solano       336.0
48           Sonoma       111.0
49       Stanislaus      1372.0
50           Sutter         0.0
51           Tehama         0.0
52          Trinity         0.0
53           Tulare      5435.0
54         Tuolumne         0.0
55          Ventura      2932.0
56             Yolo         0.0
57             Yuba         0.0

In [27]:
county_totals.sort_values(by='Case_Count',ascending=False)

             County  Case_Count
14             Kern     46138.0
18      Los Angeles     14719.0
9            Fresno     10925.0
53           Tulare      5435.0
36        San Diego      4909.0
39  San Luis Obispo      3860.0
32        Riverside      3377.0
29           Orange      3140.0
55          Ventura      2932.0
38      San Joaquin      2877.0
15            Kings      2873.0
26         Monterey      2086.0
35   San Bernardino      1983.0
6      Contra Costa      1410.0
49       Stanislaus      1372.0
23           Merced      1363.0
41    Santa Barbara      1059.0
0           Alameda      1048.0
42      Santa Clara       931.0
33       Sacramento       771.0
47           Solano       336.0
40        San Mateo       299.0
37    San Francisco       289.0
43       Santa Cruz       176.0
48           Sonoma       111.0
30           Placer       100.0
20            Marin        70.0
19           Madera        61.0
25             Mono         0.0
21         Mariposa         0.0
13             Inyo         0.0
12         Imperial         0.0
16             Lake         0.0
17           Lassen         0.0
11         Humboldt         0.0
10            Glenn         0.0
2            Amador         0.0
3             Butte         0.0
5            Colusa         0.0
4         Calaveras         0.0
7         Del Norte         0.0
8         El Dorado         0.0
1            Alpine         0.0
24            Modoc         0.0
22        Mendocino         0.0
31           Plumas         0.0
34       San Benito         0.0
27             Napa         0.0
28           Nevada         0.0
44           Shasta         0.0
46         Siskiyou         0.0
45           Sierra         0.0
51           Tehama         0.0
50           Sutter         0.0
52          Trinity         0.0
54         Tuolumne         0.0
56             Yolo         0.0
57             Yuba         0.0

In [32]:
total_all_counties = counts_by_county['Case_Count'].sum()
total_all_counties

np.float64(114650.0)

In [30]:
selected_counties = [
    'Fresno',
    'Kern',
    'Los Angeles',
    'Tulare',
    'San Diego',
    'San Luis Obispo',
    'Orange',
    'Ventura'
]

selected_county_total = counts_by_county[counts_by_county['County'].isin(selected_counties)]['Case_Count'].sum()
selected_county_total

np.float64(92058.0)

In [33]:
selected_out_of_total = selected_county_total/total_all_counties
selected_out_of_total

np.float64(0.8029481029219363)